version: '3.8'

services:
  # Custom redis server
  redis-server:
    build: .
    command: python redis_clone/server.py
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis-server # For tests
      - REDIS_PORT=9999 # For tests
    ports:
      - "9999:9999"