name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    name: Running tests
    runs-on: ubuntu-latest
    steps:
      # checkout the code
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start redis service
        run: |
          docker-compose up -d --build redis-server 
          sleep 5
      - name: run pytest
        run: |
          set -o pipefail
          docker-compose run --rm --entrypoint='bash -c "cd /usr/src/redis-clone/ && pytest -vvv"' redis-server | tee pytest_coverage.txt
      - name: bring down the services
        run: docker-compose -f docker-compose.yaml down
  